# Generated by Django 3.0.3 on 2020-02-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinnertime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindish',
            old_name='name',
            new_name='main_course',
        ),
        migrations.RenameField(
            model_name='sidedish',
            old_name='name',
            new_name='side_dish',
        ),
    ]
